### ISSUE TITLE
Need to handle all extensions

### ISSUE THREAD

**Issue by martindholmes** [projectEndings/html_diagnostics#1]
No code yet, and already I'm raising issues! This is based on the readme.

I think we should automatically check htm, html and xhtml extensions. People should be able to turn OFF specific extensions if they need to, not specify which one(s) to check.

**Comment by joeytakeda** [comment]
I'm in the process of moving things over now from the old repo to this one
(since they really separate concerns). Just making sure nothing breaks in
the move over and then committing.

But yes, that's a good idea--opting out rather than opting in.

**Comment by joeytakeda** [comment]
This should be fixed now. I've changed this so that you can specify a pattern, since we need to be able to use filesets effectively. By default, the property suffix is set as *htm*, which selects xhtml, htm, and html. If you want to choose just one of those or if you have a different suffix that you use for your XHTML files, then you can just use a different pattern.
